version: '3.1'

services:
  aws-ecs-demo:
    build:
      context: ./
      dockerfile: ./Dockerfile
      args:
        - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
        - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
        - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
        # - POSTGRES_USER=${POSTGRES_USER}
        # - POSTGRES_PW=${POSTGRES_PW}
        # - POSTGRES_HOST=${POSTGRES_HOST}
        # - POSTGRES_DB=${POSTGRES_DB}
    container_name: aws-ecs-demo
    ports:
      - 5000:5000
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      # - POSTGRES_USER=${POSTGRES_USER}
      # - POSTGRES_PW=${POSTGRES_PW}
      # - POSTGRES_HOST=${POSTGRES_HOST}
      # - POSTGRES_DB=${POSTGRES_DB}
    # bridge - connect to docker container from localhost
    network_mode: bridge
